# Generated by Django 5.1.6 on 2025-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('imdb_rating', models.FloatField()),
                ('imdb_votes', models.CharField(blank=True, max_length=50, null=True)),
                ('box_office', models.CharField(blank=True, max_length=50, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
